### PR TITLE
riscv64: fix `fenv` handling

### LINKED ISSUE #39: bionic test: fenv
Details refer to https://gitee.com/aosp-riscv/working-group/issues/I4ME6A

### PR DESCRIPTION
**Pull request by liushuyu**
This pull request fixes several issues with `fenv` handling and should close https://github.com/aosp-riscv/working-group/issues/39.

### Issues with `fesetenv`

There was a typo in `fesetenv` that prevented the `fcsr` to be set correctly. The typo has been corrected.

### Issues with `fesetexcept`

`fesetexcept` should return `-1` when the architecture does not support masking FPU exception vectors.

### Issues with `tests/fenv_test.cpp`

Since RISC-V is a RISC architecture, it should be tested like other RISC architecture: `fesetexcept` should return `-1` (indicates the platforms does not support it), and `fegetexcept` should always return `0`.

### CODE REVIEW

File: libc/include/bits/fenv_riscv64.h [hunk 1]
```diff
@@ -41,6 +41,7 @@ typedef unsigned int fenv_t;
 #define FE_OVERFLOW   0x04
 #define FE_DIVBYZERO  0x08
 #define FE_INVALID    0x10
+#define FE_DENORMAL   0x00 // compatibility
```
Comment (unicornx) [inline libc/include/bits/fenv_riscv64.h]: DENORMAL is not defined in RISCV ISA F extension, please check Table 11.2: Accrued exception flag encoding. (I use 20191213, it is still the latest official version at <https://riscv.org/technical/specifications/> )

File: tests/fenv_test.cpp [hunk 2]
```diff
@@ -181,7 +181,7 @@ TEST(fenv, fedisableexcept_fegetexcept) {
 }
 
 TEST(fenv, feenableexcept_fegetexcept) {
-#if defined(__aarch64__) || defined(__arm__)
+#if defined(__aarch64__) || defined(__arm__) || defined(__riscv)
```
Comment (unicornx) [inline tests/fenv_test.cpp]: I suggest we sync the changes from RVI upstream, FE_DENORMAL is not defined for riscv.

File: libm/riscv64/fenv.c [hunk 3]
```diff
@@ -46,7 +46,7 @@ int fesetenv(const fenv_t* envp)
 
   __get_fcw(env);
   if (*envp != env)
-	__set_fcw(env);
+	__set_fcw(*envp);
```
Comment (unicornx) [inline libm/riscv64/fenv.c]: replace the TAB with space to keep in line with coding style with others

**Comment by unicornx** [comment]
From your changes and test result, I think for this issue, we'd better catch up with RVI upstream for fenv related files.
Please correct as per my comments and keep in line with the RVI upstream. Then I will merge this PR. Any question please let me know.

**Comment by liushuyu** [comment]
Addressed comments.
